<?php
return [
    'doc'     => 'application/msword',
    'gif'     => 'image/gif',
    'html'    => 'text/html',
    'ico'     => 'image/x-icon',
    'java'    => 'java/*',
    'jpeg'    => 'image/jpeg',
    'mp4'     => 'video/mpeg4',
    'png'     => 'application/x-png',
    'ppt'     => 'application/x-ppt',
    'ps'      => 'application/postscript',
    'swf'     => 'application/x-shockwave-flash',
    'xls'     => 'application/x-xls',
    'css'     => 'text/css',
    'js'      => 'application/x-javascript',
    'png'     => 'image/png',
    'xls'     => 'application/vnd.ms-excel',
    'xlsx'    => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
];